version: "3"

services:
  website:
    image: jekyll/jekyll:3
    ports:
      - "4000:4000"
    command: jekyll serve
    volumes:
      - ./docs:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle
