version: "3"

services:
  staticWebsite:
    image: jekyll/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve
    volumes:
      - ./alexandre-huet-developpement:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle
